name: SCA - Dependency Check Caller
on:
  push:
    branches-ignore:
      - 'dependabot/*'
  workflow_dispatch:

jobs:
 SCA_caller:
      uses: eu-digital-identity-wallet/eudi-infra-ci/.github/workflows/sca_bt.yml@main
      secrets:
       NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
       DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
       DOJO_URL: ${{ secrets.DOJO_URL }}