name: Secret Scanning - Gitleaks Caller
on:
  push:
    branches-ignore:
      - 'dependabot/*'
  workflow_dispatch:

jobs:
  Secret_Scanning_caller:
      uses: eu-digital-identity-wallet/eudi-infra-ci/.github/workflows/secretscanning.yml@main
      secrets:
       DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
       DOJO_URL: ${{ secrets.DOJO_URL }}