name: SAST - SonarCloud (BT) Caller
on:
  push:
    branches-ignore:
      - 'dependabot/*'
  pull_request_target:
  workflow_dispatch:

jobs:
   SAST_caller:
      uses: eu-digital-identity-wallet/eudi-infra-ci/.github/workflows/sast_bt.yml@main
      secrets:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       DOJO_TOKEN: ${{ secrets.DOJO_TOKEN }}
       DOJO_URL: ${{ secrets.DOJO_URL }}